version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: doctorapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: MyPassword123
      MYSQL_DATABASE: doctor2
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pMyPassword123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
    driver: local