// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvvkuokkaugnrifujcai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2dmt1b2trYXVnbnJpZnVqY2FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODQ2MjEsImV4cCI6MjA2Mzc2MDYyMX0.GuQpjAY6vRl1qR4U93PoxttTmn1CJ_uPOo1DSCm39XQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);